name: Build and Version with Make

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential make

    - name: Read and bump version
      id: version
      run: |
        VERSION=$(cat version.txt | tr -d 'v')
        MAJOR=$(echo "$VERSION" | cut -d. -f1)
        MINOR=$(echo "$VERSION" | cut -d. -f2)
        NEW_MINOR=$(printf "%02d" $((10#$MINOR + 1)))
        NEW_VERSION="v$MAJOR.$NEW_MINOR"
        echo "$NEW_VERSION" > version.txt
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

    - name: Build with Makefile
      run: |
        VERSION=$(cat version.txt | tr -d 'v')
        make ci-build VERSION=$VERSION

    - name: Commit updated version
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add version.txt
        git commit -m "CI: bump version to ${{ steps.version.outputs.new_version }}" || echo "No changes to commit"
        git push

    - name: Create Git tag for release
      run: |
        git fetch --tags
        VERSION=${{ steps.version.outputs.new_version }}
        TAG_NAME="PROD_VERSION_${VERSION#v}"
        if ! git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          git push origin "$TAG_NAME"
        else
          echo "Tag $TAG_NAME already exists. Skipping tag creation."
        fi
